### PR TITLE
Add modules for IP Sets, NS Groups, Services and Firewall Section 

### PR DESCRIPTION
**Pull request by laidbackware**
Added modules to cover creation of layer-3 firewall section with rules, ip sets, ns groups and services.

Modules have been fully implemented to API spec and have been tested to be idempotent. Code handles there being objects with duplicate names and aborts if they are used and handles the API returning cursors on API requests. Module will place rules within a section and modify placement during update if placement has changed and the modify flag is set.

The comparison operations vary depending on data structures. Implemented with mixture of comparing hashes of concatenated lists strings, list comprehension to compare values is keys exist and direct comparison.

Added support for api pagination to module_utils/vmware_nsxt.py. 'request_get_all' is a drop in replacement for 'request' when performing a get, but will handle api pagination.
Also fixed a couple of python 2>3 bugs which didn't appear before.

Signed-off-by: Matt Proud proudmatt@gmail.com

### CODE REVIEW

**Comment by madhukark** [comment]
Internal bug created to review and accept the PR.

**Comment by VDI-Tech-Guy** [comment]
@madhukark  Hello this has been 8 months since this PR was created, any reason to why its not merged as of yet??

**Comment by mstrent** [comment]
Waiting eagerly on this merge. These Ansible modules are important for our organization. We have some business pending with VMWare of which distributed firewall automation is a key component.

**Comment by jgerry2002** [comment]
Makes no sense why the merge was not completed. We need IP Sets and a few other options that up stream has that are not here.

**Comment by jgerry2002** [comment]
Any chance this could be merged? @r-raghu @AkhileshK8y ?

**Comment by laidbackware** [comment]
Cancelling PR due to lack of contact and the planned manager API deprecation.

**Pull request closed without merging**
